src/App/Utilities/YAML/ZipById.ts
=> zipBy and mergeBy should remove duplicates

app/Docs/nl-BE/FAQ.md
I am unsure what the Armor things are about, so i left them untranslated, I'll look it up and check it in later.
=> First attempt at Dutch translation for FAQ

app/index.html, src/entry.tsx
=> Bugfix: UI Zoom

src/App/Views/InlineWiki/WikiSpellInfo.tsx
=> Bugfix: Missing range and duration for tricks

src/App/Selectors/equipmentSelectors.ts, src/App/Utilities/Chars.ts, src/App/Views/Sheets/CombatSheet/CombatSheetMeleeWeapons.tsx
=> Bugfix: Missing lances character sheet

app/Docs/it-IT/CHANGELOG.md, app/Docs/it-IT/FAQ.md
CHANGELOG.md and FAQ.md localized to Italian
=> Docs localization in Italian

src/App/Utilities/Activatable/activatableInactiveViewUtils.tsx, src/App/Utilities/Activatable/activatableNameUtils.ts, src/App/Utilities/AdventurePoints/activatableCostUtils.ts
=> Enable multiselect for Kind der Natur and similar special abilities

src/App/Utilities/Activatable/activatableNameUtils.ts
=> Bugfix: SA Fachwissen unexpected chars

src/App/Selectors/raceSelectors.ts, src/App/Selectors/wikiSelectors.ts, src/App/Utilities/Activatable/activatableInactiveUtils.ts, src/App/Views/InlineWiki/WikiActivatableInfo.tsx, src/App/Views/LiturgicalChants/LiturgicalChants.tsx
=> Fix: Aspect Knowledge

src/App/Selectors/spellsSelectors.ts
=> Fix: Witch's Gaze restriction

src/App/Actions/InitializationActions.ts, src/App/Models/Wiki/ArcaneBardTradition.ts, src/App/Models/Wiki/ArcaneDancerTradition.ts, src/App/Models/Wiki/WikiModel.ts, src/App/Utilities/Activatable/activatableInactiveViewUtils.tsx, src/App/Utilities/Activatable/activatableNameUtils.ts, src/App/Utilities/YAML.ts, src/App/Utilities/YAML/Entries/ToAdvantages.ts, src/App/Utilities/YAML/Entries/ToArcaneBardTraditions.ts, src/App/Utilities/YAML/Entries/ToArcaneDancerTraditions.ts, src/App/Utilities/YAML/Entries/ToDisadvantages.ts, src/App/Utilities/YAML/Entries/ToSpecialAbilities.ts, src/App/Utilities/YAML/ParseByFile.ts, src/App/Utilities/YAML/SchemaMap.ts, src/App/Utilities/YAML/ToRecordsByFile.ts, src/App/Views/InlineWiki/Elements/WikiSpellTraditions.tsx, src/entry.tsx
=> Fix: Arcane traditions prerequisites

src/App/Views/InlineWiki/WikiProfessionInfo.tsx, src/App/Views/RCPOptionSelections/CombatTechniqueSelectionList.tsx
=> Fix: Second combat technique bonus in professions

src/App/Utilities/I18n.ts
=> Fix: Floor values with a unit on character sheet

src/App/Containers/SettingsContainer.ts, src/App/Utilities/CheckForUpdates.ts, src/App/Utilities/CheckForUpdatesMain.ts, src/App/Utilities/CheckForUpdatesRenderer.ts, src/App/Views/Settings/Settings.tsx, src/main.ts
Closes #589.
Hopefully closes #573.
=> fix: Disable updater on systems where it does not work

src/App/Selectors/liturgicalChantsSelectors.ts
Fixed SA Zugvoegel functionality if a chant is available for both the unfamiliar and the familiar tradition.
Closes #677.
=> fix: SA Zugvoegel multiple traditions

app/Docs/de-DE/CHANGELOG.md, app/Docs/en-US/CHANGELOG.md, app/Docs/fr-FR/CHANGELOG.md, app/Docs/nl-BE/CHANGELOG.md, src/App/Constants/Ids.ts, src/App/Models/View/ActivatableNameCost.ts, src/App/Models/View/ActiveActivatable.ts, src/App/Utilities/Activatable/activatableNameUtils.ts, src/App/Views/Activatable/ActivatableAddListItem.tsx
=> feat: Custom Entries – temporary solution

src/App/Actions/IOActions.ts
=> fix: JSON export missing extension

.github/workflows/prerelease.yml, .github/workflows/release.yml, .gitignore, package-lock.json, package.json, src/index.html, webpack.config.js
=> build: Added webpack

.github/ISSUE_TEMPLATE/bug_report.md
For better readability after filling out the form.
=> Update: issue template bug_report.md

.github/ISSUE_TEMPLATE/feature_request.md
For better readability after filling out the form.
=> Update: issue template feature_request.md

.github/ISSUE_TEMPLATE/new-book-data.md
=> Update: issue template new-book-data.md

.github/ISSUE_TEMPLATE/publication-bug-report.md
=> Update: issue template publication-bug-report.md

src/App/Views/InlineWiki/WikiActivatableInfo.tsx
=> Race prerequisite does not display race required #1093

package-lock.json, package.json, src/main.ts
This fixes the crash when installing the extensions
=> Updates electron-devtools-installer
